import { useState } from 'react';
import { ArrowRight, Check, Clock3, LogOut, Pencil, Search, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import EmptyState from '../components/EmptyState';
import { useAuth } from '../context/AuthContext';
import { useMealActivity } from '../context/MealActivityContext';
import { useMeals } from '../context/MealContext';

const diets = ['No preference', 'Vegetarian', 'Vegan', 'Eggitarian', 'Non-vegetarian'];
const times = ['10 min', '20 min', '30 min', '45 min', '1 hour+'];
const budgets = ['₹0', '₹50', '₹100', '₹200+', 'No limit'];
const spices = ['Mild', 'Medium', 'Spicy'];
const equipment = ['Gas Stove', 'Induction', 'Microwave', 'Oven', 'Air Fryer', 'Pressure Cooker', 'Kettle', 'Pan', 'Pot'];

function initials(name) {
  const parts = (name || 'Meal Planner User').trim().split(/\s+/).filter(Boolean);
  return parts.length > 1 ? `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase() : parts[0][0].toUpperCase();
}

function ChoiceField({ label, value, options, onChange }) {
  return <label className="block text-sm font-bold text-ink">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-line bg-cream px-3 py-3 text-sm font-medium text-ink outline-none focus:border-saffron focus:ring-2 focus:ring-saffron/20">{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
}

function ProfileHeader({ currentUser, onSaveName }) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(currentUser.displayName || '');
  const [error, setError] = useState('');
  const save = async () => { if (!name.trim()) { setError('Please enter your name.'); return; } setError(''); try { await onSaveName(name.trim()); setEditing(false); } catch { setError('Unable to update your profile. Please try again.'); } };
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-3xl bg-saffron text-2xl font-extrabold text-white shadow-card">{initials(currentUser.displayName)}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.16em] text-saffron">Account</p>{editing ? <div className="mt-2 flex flex-wrap gap-2"><input value={name} onChange={(event) => setName(event.target.value)} className="min-w-[220px] flex-1 rounded-xl border border-line bg-cream px-3 py-2 text-sm outline-none focus:border-saffron" /><button type="button" onClick={save} className="rounded-xl bg-ink px-4 py-2 text-sm font-bold text-white">Save changes</button><button type="button" onClick={() => setEditing(false)} className="rounded-xl border border-line px-4 py-2 text-sm font-bold text-ink">Cancel</button></div> : <div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="font-display text-3xl text-ink">{currentUser.displayName || 'Meal Planner User'}</h2><button type="button" onClick={() => setEditing(true)} aria-label="Edit display name" className="grid h-8 w-8 place-items-center rounded-full border border-line text-muted hover:border-saffron hover:text-ink"><Pencil size={14} /></button></div>}<p className="mt-1 truncate text-sm text-muted">{currentUser.email}</p>{error && <p className="mt-2 text-xs font-semibold text-red-700">{error}</p>}<p className="mt-3 inline-flex items-center gap-1.5 text-xs font-bold text-sage-deep"><Check size={14} /> Account active</p></div></div></section>;
}

function Stats({ recentSearches, recentlyViewed, savedMeals }) {
  return <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-line bg-white p-5"><Search size={18} className="text-saffron" /><p className="mt-5 text-3xl font-extrabold text-ink">{recentSearches.length}</p><p className="mt-1 text-sm text-muted">Recipes searched</p></div><div className="rounded-2xl border border-line bg-white p-5"><Clock3 size={18} className="text-saffron" /><p className="mt-5 text-3xl font-extrabold text-ink">{recentlyViewed.length}</p><p className="mt-1 text-sm text-muted">Recipes viewed</p></div><div className="rounded-2xl border border-line bg-white p-5"><Check size={18} className="text-saffron" /><p className="mt-5 text-3xl font-extrabold text-ink">{savedMeals.length}</p><p className="mt-1 text-sm text-muted">Saved meals</p></div></div>;
}

function Preferences({ preferences, updatePreferences }) {
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-saffron">Personalise your planning</p><h2 className="mt-2 font-display text-3xl text-ink">Meal Preferences</h2><p className="mt-2 text-sm leading-6 text-muted">Set your defaults for more useful recommendations.</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><ChoiceField label="Dietary preference" value={preferences.diet} options={diets} onChange={(diet) => updatePreferences({ diet })} /><ChoiceField label="Preferred cooking time" value={preferences.time} options={times} onChange={(time) => updatePreferences({ time })} /><ChoiceField label="Default budget" value={preferences.budget} options={budgets} onChange={(budget) => updatePreferences({ budget })} /><ChoiceField label="Spice preference" value={preferences.spicePreference} options={spices} onChange={(spicePreference) => updatePreferences({ spicePreference })} /></div><div className="mt-5"><p className="text-sm font-bold text-ink">Cooking equipment</p><div className="mt-3 flex flex-wrap gap-2">{equipment.map((item) => { const selected = preferences.equipment.includes(item); return <button type="button" key={item} onClick={() => updatePreferences({ equipment: selected ? preferences.equipment.filter((value) => value !== item) : [...preferences.equipment, item] })} className={`rounded-full border px-3 py-2 text-xs font-bold ${selected ? 'border-sage bg-sage text-sage-deep' : 'border-line text-muted hover:border-saffron hover:text-ink'}`}>{item}</button>; })}</div></div><label className="mt-5 block text-sm font-bold text-ink" htmlFor="profile-restrictions">Food restrictions<textarea id="profile-restrictions" rows="3" value={preferences.restrictions} onChange={(event) => updatePreferences({ restrictions: event.target.value })} placeholder="No peanuts, less dairy" className="mt-2 w-full resize-none rounded-xl border border-line bg-cream px-4 py-3 text-sm font-normal outline-none focus:border-saffron focus:ring-2 focus:ring-saffron/20" /></label></section>;
}

function RecentSearches({ searches }) {
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><h2 className="font-display text-3xl text-ink">Recent Meal Searches</h2>{searches.length ? <div className="mt-6 divide-y divide-line">{searches.map((search) => <div key={search.id} className="py-5 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-4"><div><p className="font-bold capitalize text-ink">{search.mealType || 'Meal'} planning</p><p className="mt-1 text-sm text-muted">{search.ingredients.join(', ')}</p><p className="mt-2 text-xs font-semibold text-muted">{search.time} • {search.budget} • {search.diet}</p></div><Link to="/results" className="inline-flex shrink-0 items-center gap-1 text-xs font-bold text-ink hover:text-sage-deep">View results <ArrowRight size={14} /></Link></div></div>)}</div> : <EmptyState title="No meal searches yet." description="Your meal searches will appear here." action={<Link to="/plan" className="mt-6 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Plan your first meal <ArrowRight size={16} /></Link>} />}</section>;
}

function RecipeList({ title, recipes, emptyTitle, emptyDescription, action, onRemove }) {
  return <section className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><h2 className="font-display text-3xl text-ink">{title}</h2>{recipes.length ? <div className="mt-6 grid gap-3">{recipes.map((recipe) => <div key={recipe.id} className="flex items-center gap-4 rounded-2xl border border-line p-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-saffron/15 text-2xl">{recipe.emoji}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-ink">{recipe.name}</p><p className="mt-1 text-xs text-muted">{recipe.time} min • {recipe.difficulty}</p></div><Link to={`/recipe/${recipe.id}`} className="inline-flex shrink-0 items-center gap-1 text-xs font-bold text-ink hover:text-sage-deep">View recipe <ArrowRight size={14} /></Link>{onRemove && <button type="button" onClick={() => onRemove(recipe.id)} className="text-xs font-bold text-muted hover:text-red-700">Remove</button>}</div>)}</div> : <EmptyState title={emptyTitle} description={emptyDescription} action={action} />}</section>;
}

export default function Profile() {
  const navigate = useNavigate();
  const { currentUser, loading, logout, updateDisplayName } = useAuth();
  const { recentSearches, recentlyViewed, preferences, updatePreferences, loading: activityLoading, error: activityError } = useMealActivity();
  const { savedMeals, removeSaved } = useMeals();
  if (loading || activityLoading || !currentUser) return <main className="grid min-h-[60vh] place-items-center px-5 py-16"><p className="font-display text-3xl text-ink">Loading your profile...</p></main>;
  const handleLogout = async () => { await logout(); navigate('/'); };
  return <main className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-saffron">Your kitchen notebook</p><h1 className="mt-3 font-display text-5xl leading-tight text-ink">Your Profile</h1><p className="mt-4 text-base leading-7 text-muted">Manage your account and meal-planning activity.</p></div><div className="mt-9 grid gap-5 lg:grid-cols-[0.82fr_1.18fr]"><div className="space-y-5"><ProfileHeader currentUser={currentUser} onSaveName={updateDisplayName} /><Stats recentSearches={recentSearches} recentlyViewed={recentlyViewed} savedMeals={savedMeals} /><Preferences preferences={preferences} updatePreferences={updatePreferences} /><section className="rounded-3xl border border-line bg-white p-6 shadow-card"><h2 className="font-display text-3xl text-ink">Account</h2><div className="mt-5 flex items-center justify-between gap-4 text-sm"><span className="text-muted">{currentUser.email}</span><span className="font-bold text-sage-deep">Active</span></div><button type="button" onClick={handleLogout} className="mt-6 inline-flex items-center gap-2 rounded-full border border-line px-5 py-3 text-sm font-bold text-ink hover:border-ink"><LogOut size={16} /> Log out</button></section></div><div className="space-y-5"><RecentSearches searches={recentSearches} /><RecipeList title="Recently Viewed" recipes={recentlyViewed} emptyTitle="No recipes viewed yet." emptyDescription="Open a recipe from your recommendations to see it here." action={<Link to="/plan" className="mt-6 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Explore meals <ArrowRight size={16} /></Link>} /><RecipeList title="Saved Meals" recipes={savedMeals} emptyTitle="No saved meals yet." emptyDescription="Save recipes you want to cook later." action={<Link to="/plan" className="mt-6 inline-flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Explore meals <ArrowRight size={16} /></Link>} onRemove={removeSaved} /></div></div></main>;
}
