import { ArrowRight, Bookmark, Clock3, IndianRupee, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useMeals } from '../context/MealContext';

export default function MealCard({ meal, compact = false }) {
  const { savedMeals, toggleSaved } = useMeals();
  const saved = savedMeals.some((item) => item.id === meal.id);
  return <article className={`group flex h-full flex-col rounded-3xl border border-line bg-white p-5 shadow-card transition-all hover:-translate-y-1 hover:shadow-soft ${compact ? '' : 'sm:p-6'}`}><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-saffron/15 text-2xl">{meal.emoji}</div><button type="button" aria-label={saved ? `Remove ${meal.name} from saved meals` : `Save ${meal.name}`} onClick={() => toggleSaved(meal)} className={`grid h-10 w-10 place-items-center rounded-full border transition-colors ${saved ? 'border-saffron bg-saffron/10 text-saffron' : 'border-line text-muted hover:border-saffron hover:text-saffron'}`}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'} /></button></div><div className="mt-5"><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-sage-deep"><span>{meal.diet}</span><span className="h-1 w-1 rounded-full bg-sage-deep/40" /><span>{meal.difficulty}</span></div><h3 className="mt-2 font-display text-[27px] leading-tight text-ink">{meal.name}</h3><p className="mt-2 text-sm leading-6 text-muted">{meal.description}</p></div><div className="mt-5 flex flex-wrap gap-2 border-y border-line py-4 text-xs font-semibold text-muted"><span className="inline-flex items-center gap-1.5"><Clock3 size={14} className="text-saffron" /> {meal.time} min</span><span className="inline-flex items-center gap-1.5"><IndianRupee size={14} className="text-saffron" /> {meal.additionalCost} additional</span></div><div className="mt-4 flex-1"><p className="mb-2 flex items-center gap-1.5 text-xs font-bold uppercase tracking-[0.12em] text-ink"><Sparkles size={14} className="text-saffron" /> Why it fits</p><p className="text-sm leading-6 text-muted">{meal.whyItFits}</p></div><Link to={`/recipe/${meal.id}`} className="mt-6 inline-flex items-center justify-center gap-2 rounded-full bg-ink px-4 py-3 text-sm font-bold text-white transition-colors hover:bg-sage-deep">View recipe <ArrowRight size={16} /></Link></article>;
}
