import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { ChefHat, Menu, X } from 'lucide-react';

const links = [['Home', '/'], ['Plan a Meal', '/plan'], ['Saved Meals', '/saved']];
export default function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-30 border-b border-line/80 bg-cream/90 backdrop-blur-lg"><div className="mx-auto flex h-[74px] max-w-6xl items-center justify-between px-5"><Link to="/" className="flex items-center gap-2.5" onClick={() => setOpen(false)}><span className="grid h-9 w-9 place-items-center rounded-xl bg-saffron text-white shadow-sm"><ChefHat size={20} /></span><span className="font-display text-xl tracking-tight text-ink">AI Meal Planner</span></Link><nav className="hidden items-center gap-8 md:flex">{links.map(([label, href]) => <NavLink key={href} to={href} className={({ isActive }) => `text-sm font-semibold transition-colors ${isActive ? 'text-ink' : 'text-muted hover:text-ink'}`}>{label}</NavLink>)}<Link to="/plan" className="rounded-full bg-ink px-5 py-2.5 text-sm font-bold text-white transition-transform hover:-translate-y-0.5">Get started</Link></nav><button type="button" aria-label={open ? 'Close menu' : 'Open menu'} className="grid h-10 w-10 place-items-center rounded-full border border-line bg-white text-ink md:hidden" onClick={() => setOpen(!open)}>{open ? <X size={19} /> : <Menu size={19} />}</button></div>{open && <nav className="border-t border-line bg-cream px-5 pb-5 pt-3 md:hidden">{links.map(([label, href]) => <NavLink key={href} to={href} onClick={() => setOpen(false)} className="block border-b border-line py-3 text-sm font-semibold text-ink">{label}</NavLink>)}<Link to="/plan" onClick={() => setOpen(false)} className="mt-4 block rounded-full bg-ink px-5 py-3 text-center text-sm font-bold text-white">Get started</Link></nav>}</header>;
}
